const ShopActionTypes = {
  UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
  OPEN_PRODUCT_DETAIL: "OPEN_PRODUCT_DETAIL",
  SET_CATEGORY_SLUG: "SET_CATEGORY_SLUG",
  SET_CATEGORY_MENU: "SET_CATEGORY_MENU",
};

export default ShopActionTypes;
